services:

  db:
    image: mysql:9.3.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: cat-cool-dog-fun-foo-bar-1234567890
      MYSQL_DATABASE: parent_diary
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

  next-web-app:
    build:
      context: ./parent-diary-nextjs-web-app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  nest-rest-api:
    build:
      context: ./parent-diary-nestjs-rest-api
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: cat-cool-dog-fun-foo-bar-1234567890
      DB_DATABASE: parent_diary
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
