services:

  db:
    image: mysql:9.3.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: parent_diary
    volumes:
      - ./mysql_data:/var/lib/mysql
